# -*- coding: utf-8 -*-
"""cardiac ml final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6BrFxQZKPl6jNHW9DM8qwpgttS_c97H
"""

# Cell 1 — database
!pip install wfdb requests -q

# wave form database
import wfdb
import requests
import numpy as np
import pandas as pd
import io

# ── 1. normal - mit bih sinus rhythm) ──────────────────────────
print("=== nsrdb (NORMAL) ===")
normal_records = wfdb.get_record_list('nsrdb')
print(f"Records found: {len(normal_records)}")
print(f"First 5: {normal_records[:5]}")

# ── 2. active - pulse transit time ppg) ─────────
print("\n=== pulse-transit-time-ppg (ACTIVE) ===")
ptt_records = wfdb.get_record_list('pulse-transit-time-ppg')
print(f"Records found: {len(ptt_records)}")
print(f"First 5: {ptt_records[:5]}")

# ── 3. stressed - wearable exam stress  ───────────
print("\n=== wearable-exam-stress (STRESSED) ===")
url = "https://physionet.org/files/wearable-exam-stress/1.0.0/data/S1/Final/IBI.csv"
r = requests.get(url)
print(f"HTTP status: {r.status_code}")
if r.status_code == 200:
    ibi_test = pd.read_csv(io.StringIO(r.text), header=None, skiprows=1)
    print(f"IBI sample shape: {ibi_test.shape}")
    print(f"First 3 rows:\n{ibi_test.head(3)}")
    print("✓ Stress dataset accessible")
else:
    print(f"✗ Failed — status {r.status_code}")

print("\n✓ Done")

import numpy as np

rec = normal_records[0]
print(f"Inspecting record: {rec}")

ann = wfdb.rdann(rec, 'atr', pn_dir='nsrdb')

print(f"Total beats found: {len(ann.sample)}")
print(f"Sample indices (first 10): {ann.sample[:10]}")

rr = np.diff(ann.sample) / 128.0
print(f"\nRR intervals (first 10): {rr[:10].round(4)}")
print(f"RR min: {rr.min():.3f}s   RR max: {rr.max():.3f}s")
print(f"Beats after filter (0.25-2.5s): {np.sum((rr > 0.25) & (rr < 2.5))}")

# extracting features

import wfdb
import requests
import numpy as np
import pandas as pd
import io

# computing features for each dataset, and adding synthetic data for blood oxygen and motion

def compute_features_from_rr(rr_seconds, window_size=60, step=30):
    features = []
    rr = np.array(rr_seconds, dtype=float)
    rr = rr[(rr > 0.25) & (rr < 2.5)]
    if len(rr) < window_size:
        return features
    for start in range(0, len(rr) - window_size, step):
        window   = rr[start:start + window_size]
        bpm_mean = 60.0 / np.mean(window)
        diff     = np.diff(window)
        rmssd    = np.sqrt(np.mean(diff**2)) * 1000
        sdnn     = np.std(window) * 1000
        features.append([bpm_mean, rmssd, sdnn])
    return features

def add_synthetic_cols(features, label,
                       spo2_mean, spo2_std,
                       motion_mean_range, motion_std_range):
    n   = len(features)
    arr = np.array(features)
    spo2     = np.clip(np.random.normal(spo2_mean, spo2_std, n), 90, 100)
    mot_mean = np.random.uniform(*motion_mean_range, n)
    mot_std  = np.random.uniform(*motion_std_range,  n)
    return pd.DataFrame({
        'bpm_mean':    arr[:, 0],
        'hrv_rmssd':   arr[:, 1],
        'hrv_sdnn':    arr[:, 2],
        'spo2':        spo2,
        'motion_mean': mot_mean,
        'motion_std':  mot_std,
        'label':       label
    })


# class 0: normal
print("Loading NORMAL (nsrdb)...")
normal_features = []

for rec in wfdb.get_record_list('nsrdb'):
    try:
        ann   = wfdb.rdann(rec, 'atr', pn_dir='nsrdb')
        rr    = np.diff(ann.sample) / 128.0
        feats = compute_features_from_rr(rr)
        normal_features.extend(feats)
    except Exception as e:
        print(f"  Skipping {rec}: {e}")

print(f"  Windows extracted: {len(normal_features)}")
df_normal = add_synthetic_cols(
    normal_features, label=0,
    spo2_mean=98, spo2_std=1.0,
    motion_mean_range=(0.9, 1.1),
    motion_std_range=(0.02, 0.08)
)


# class 1: active (using annotations)
print("\nLoading ACTIVE (pulse-transit-time-ppg, annotations only)...")
active_features = []
ptt_records     = wfdb.get_record_list('pulse-transit-time-ppg')
run_records     = [r for r in ptt_records if 'run' in r]
print(f"  Run records found: {len(run_records)}")

for i, rec in enumerate(run_records):
    try:
        ann   = wfdb.rdann(rec, 'atr', pn_dir='pulse-transit-time-ppg')
        rr    = np.diff(ann.sample) / 500.0  # 500Hz sampling rate
        feats = compute_features_from_rr(rr, window_size=40, step=20)
        active_features.extend(feats)
        print(f"  [{i+1}/{len(run_records)}] {rec} → {len(feats)} windows")
    except Exception as e:
        print(f"  Skipping {rec}: {e}")

print(f"  Total windows extracted: {len(active_features)}")
df_active = add_synthetic_cols(
    active_features, label=1,
    spo2_mean=97, spo2_std=1.0,
    motion_mean_range=(2.0, 5.0),
    motion_std_range=(0.5, 1.5)
)


# class 2: stressed
print("\nLoading STRESSED (wearable-exam-stress)...")
stress_features = []
subjects        = [f'S{i}' for i in range(1, 11)]
sessions        = ['Midterm 1', 'Midterm 2', 'Final']

for subj in subjects:
    for sess in sessions:
        sess_encoded = sess.replace(' ', '%20')
        url = (f"https://physionet.org/files/wearable-exam-stress"
               f"/1.0.0/data/{subj}/{sess_encoded}/IBI.csv")
        try:
            r = requests.get(url, timeout=10)
            if r.status_code != 200:
                continue
            raw   = pd.read_csv(io.StringIO(r.text), header=None, skiprows=1)
            rr    = raw.iloc[:, 1].values
            feats = compute_features_from_rr(rr, window_size=40, step=20)
            stress_features.extend(feats)
        except Exception as e:
            print(f"  Skipping {subj}/{sess}: {e}")

print(f"  Windows extracted: {len(stress_features)}")
df_stressed = add_synthetic_cols(
    stress_features, label=2,
    spo2_mean=97, spo2_std=1.5,
    motion_mean_range=(0.9, 1.2),
    motion_std_range=(0.02, 0.10)
)


# class 3: alert (synthetic)
print("\nGenerating ALERT (synthetic)...")
N = min(len(df_normal), len(df_active), len(df_stressed), 300)
np.random.seed(42)

df_alert = pd.DataFrame({
    'bpm_mean':    np.random.uniform(40, 170, N),
    'hrv_rmssd':   np.random.uniform(1, 12, N),
    'hrv_sdnn':    np.random.uniform(1, 12, N),
    'spo2':        np.clip(np.random.normal(90, 2, N), 85, 93),
    'motion_mean': np.random.uniform(0.9, 3.0, N),
    'motion_std':  np.random.uniform(0.02, 1.5, N),
    'label':       3
})
print(f"  Rows generated: {len(df_alert)}")


# ── COMBINE ────────────────────────────────────────────────────────────────
print("\nCombining all classes...")
df = pd.concat([df_normal, df_active, df_stressed, df_alert],
               ignore_index=True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"\nFinal dataset shape: {df.shape}")
print(f"\nSamples per class:\n{df['label'].value_counts().sort_index()}")
print(f"\nFeature ranges:\n{df.describe().round(2)}")

# upsampling stressed to 800 w/ more noise in synthetic data, downsizing normal and stressed to 800, active kept as is

TARGET = 800
np.random.seed(42)

def upsample_with_noise(df_class, target_n):
    """
    Duplicates rows with tiny gaussian noise to reach target_n.
    Noise is small enough to stay physiologically valid.
    Only adds noise to numeric feature columns, not the label.
    """
    feature_cols = ['bpm_mean', 'hrv_rmssd', 'hrv_sdnn',
                    'spo2', 'motion_mean', 'motion_std']

    current = df_class.copy()
    needed  = target_n - len(current)

    # sample 'needed' rows randomly (with replacement) and add noise
    extras  = current.sample(n=needed, replace=True, random_state=42).copy()

    # noise scale is 1% of each feature's std — tiny perturbation
    for col in feature_cols:
        noise_scale = current[col].std() * 0.01
        extras[col] = extras[col] + np.random.normal(0, noise_scale, len(extras))

    # clip spo2 back to valid range after noise
    extras['spo2'] = extras['spo2'].clip(85, 100)

    upsampled = pd.concat([current, extras], ignore_index=True)
    return upsampled


# downsample NORMAL — it has 59864, we only want 800 (random picked)
df_normal_bal   = df_normal.sample(n=TARGET, random_state=42)

# ACTIVE is already 795 — keep all of it
df_active_bal   = df_active.copy()

# downsample STRESSED — it has 1381, we only want 800 (ramdomly picked)
df_stressed_bal = df_stressed.sample(n=TARGET, random_state=42)

# upsample ALERT from 300 → 800
df_alert_bal    = upsample_with_noise(df_alert, TARGET)

# combine and shuffle
df_balanced = pd.concat([
    df_normal_bal,
    df_active_bal,
    df_stressed_bal,
    df_alert_bal
], ignore_index=True)

df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Balanced dataset shape: {df_balanced.shape}")
print(f"\nSamples per class:\n{df_balanced['label'].value_counts().sort_index()}")
print(f"\nFeature ranges:\n{df_balanced.describe().round(2)}")

# Cell 4b — save everything to Google Drive
from google.colab import drive
import joblib
import numpy as np

drive.mount('/content/drive')

SAVE_PATH = '/content/drive/MyDrive/tinyml_physio/'

import os
os.makedirs(SAVE_PATH, exist_ok=True)

# save the balanced dataset
df_balanced.to_csv(SAVE_PATH + 'df_balanced.csv', index=False)
print("✓ df_balanced saved")

# save the raw class dataframes too in case you need them
df_normal.to_csv(SAVE_PATH + 'df_normal.csv', index=False)
df_active.to_csv(SAVE_PATH + 'df_active.csv', index=False)
df_stressed.to_csv(SAVE_PATH + 'df_stressed.csv', index=False)
df_alert.to_csv(SAVE_PATH + 'df_alert.csv', index=False)
print("✓ Individual class DataFrames saved")

print(f"\nAll files saved to: {SAVE_PATH}")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib

FEATURE_COLS = ['bpm_mean', 'hrv_rmssd', 'hrv_sdnn',
                'spo2', 'motion_mean', 'motion_std']

X = df_balanced[FEATURE_COLS].values
y = df_balanced['label'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

joblib.dump(scaler, SAVE_PATH + 'scaler.pkl')

print(f"X_train: {X_train.shape}  X_test: {X_test.shape}")
print(f"\nClass distribution in train:")
unique, counts = np.unique(y_train, return_counts=True)
for u, c in zip(unique, counts):
    print(f"  class {u}: {c} samples")
print(f"\nScaler means:  {scaler.mean_.round(3)}")
print(f"Scaler stds:   {scaler.scale_.round(3)}")
print("✓ Scaler saved")

import tensorflow as tf
from tensorflow import keras

# reproducibility
tf.random.set_seed(42)
np.random.seed(42)

model = keras.Sequential([
    keras.layers.Input(shape=(6,)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(4,  activation='softmax')
], name='physio_classifier')

model.summary()

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train_scaled, y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

print("\n✓ Training complete")

from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

loss, acc = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Test accuracy: {acc:.4f}  |  Test loss: {loss:.4f}\n")

y_pred = np.argmax(model.predict(X_test_scaled), axis=1)

print(classification_report(y_test, y_pred,
      target_names=['NORMAL','ACTIVE','STRESSED','ALERT']))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['NORMAL','ACTIVE','STRESSED','ALERT'],
            yticklabels=['NORMAL','ACTIVE','STRESSED','ALERT'])
plt.title('Confusion Matrix')
plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.tight_layout()
plt.savefig(SAVE_PATH + 'confusion_matrix.png')
plt.show()
print("✓ Confusion matrix saved")

# convert to TFLite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# save .tflite file
tflite_path = SAVE_PATH + 'physio_model.tflite'
with open(tflite_path, 'wb') as f:
    f.write(tflite_model)

size_kb = len(tflite_model) / 1024
print(f"TFLite model size: {size_kb:.1f} KB")

# save keras model too as backup
model.save(SAVE_PATH + 'physio_model.keras')
print("✓ Keras model saved")
print("✓ TFLite model saved")
print(f"\nAll outputs in: {SAVE_PATH}")

from google.colab import drive
drive.mount('/content/drive')

SAVE_PATH = '/content/drive/MyDrive/tinyml_physio/'

with open(SAVE_PATH + 'physio_model.tflite', 'rb') as f:
    tflite_bytes = f.read()

c_array = ', '.join([f'0x{b:02x}' for b in tflite_bytes])
c_code  = f'alignas(8) const unsigned char model_data[] = {{\n  {c_array}\n}};\n'
c_code += f'const int model_data_len = {len(tflite_bytes)};\n'

with open(SAVE_PATH + 'model_data.h', 'w') as f:
    f.write(c_code)

print(f"Model size: {len(tflite_bytes)} bytes")
print(f"✓ model_data.h saved to Drive")

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
import numpy as np

SAVE_PATH = '/content/drive/MyDrive/tinyml_physio/'

# load trained model
model = tf.keras.models.load_model(SAVE_PATH + 'physio_model.keras')

# extract weights from each layer
w0, b0 = model.layers[0].get_weights()  # Dense(32)
w1, b1 = model.layers[1].get_weights()  # Dense(16)
w2, b2 = model.layers[2].get_weights()  # Dense(4)

def array_to_c(arr, name, dtype="float"):
    flat = arr.flatten()
    vals = ", ".join([f"{v:.6f}f" for v in flat])
    if arr.ndim == 2:
        rows, cols = arr.shape
        return f"const {dtype} {name}[{rows}][{cols}] = {{{vals}}};\n"
    else:
        size = len(flat)
        return f"const {dtype} {name}[{size}] = {{{vals}}};\n"

# scaler constants
scaler_means = [93.904, 39.693, 39.847, 95.504, 1.867, 0.463]
scaler_stds  = [24.918, 61.147, 41.127,  3.444, 1.135, 0.491]

header = """// model_weights.h
// Auto-generated from trained Keras model
// Do not edit manually

#ifndef MODEL_WEIGHTS_H
#define MODEL_WEIGHTS_H

#include <math.h>

// ── Scaler constants ──────────────────────────────────
const float SCALER_MEAN[6] = {""" + ", ".join([f"{v:.6f}f" for v in scaler_means]) + """};
const float SCALER_STD[6]  = {""" + ", ".join([f"{v:.6f}f" for v in scaler_stds]) + """};

// ── Layer 0: Dense(6 → 32, relu) ─────────────────────
""" + array_to_c(w0, "W0") + array_to_c(b0, "b0") + """
// ── Layer 1: Dense(32 → 16, relu) ────────────────────
""" + array_to_c(w1, "W1") + array_to_c(b1, "b1") + """
// ── Layer 2: Dense(16 → 4, softmax) ──────────────────
""" + array_to_c(w2, "W2") + array_to_c(b2, "b2") + """
// ── Inference function ────────────────────────────────
inline void run_model(float* input, float* output) {
    float layer0[32];
    float layer1[16];

    // Layer 0 — Dense + ReLU
    for (int j = 0; j < 32; j++) {
        float sum = b0[j];
        for (int i = 0; i < 6; i++) {
            sum += input[i] * W0[i][j];
        }
        layer0[j] = sum > 0 ? sum : 0;  // ReLU
    }

    // Layer 1 — Dense + ReLU
    for (int j = 0; j < 16; j++) {
        float sum = b1[j];
        for (int i = 0; i < 32; i++) {
            sum += layer0[i] * W1[i][j];
        }
        layer1[j] = sum > 0 ? sum : 0;  // ReLU
    }

    // Layer 2 — Dense + Softmax
    float max_val = -1e9;
    for (int j = 0; j < 4; j++) {
        float sum = b2[j];
        for (int i = 0; i < 16; i++) {
            sum += layer1[i] * W2[i][j];
        }
        output[j] = sum;
        if (sum > max_val) max_val = sum;
    }

    // softmax
    float exp_sum = 0;
    for (int j = 0; j < 4; j++) {
        output[j] = exp(output[j] - max_val);
        exp_sum += output[j];
    }
    for (int j = 0; j < 4; j++) {
        output[j] /= exp_sum;
    }
}

#endif
"""

with open(SAVE_PATH + 'model_weights.h', 'w') as f:
    f.write(header)

print(f"✓ model_weights.h saved to Drive")
print(f"File size: {len(header)} characters")

# verify it works in Python first
def run_model_python(raw_features):
    # scale
    scaled = [(raw_features[i] - scaler_means[i]) / scaler_stds[i]
              for i in range(6)]
    x = np.array(scaled)

    # layer 0
    l0 = np.maximum(0, x @ w0 + b0)
    # layer 1
    l1 = np.maximum(0, l0 @ w1 + b1)
    # layer 2 + softmax
    l2 = l1 @ w2 + b2
    probs = np.exp(l2 - l2.max()) / np.exp(l2 - l2.max()).sum()
    return probs

class_names = ['NORMAL', 'ACTIVE', 'STRESSED', 'ALERT']

print("\nVerifying model weights with test cases:")
tests = [
    ([72.0, 45.0, 50.0, 98.0, 1.0,  0.05], "NORMAL"),
    ([145.0, 25.0, 30.0, 97.0, 3.5, 0.9],  "ACTIVE"),
    ([95.0,  8.0,  9.0, 97.5, 1.0, 0.05],  "STRESSED"),
    ([130.0, 5.0,  4.0, 89.0, 1.5, 0.3],   "ALERT"),
]

for features, expected in tests:
    probs = run_model_python(features)
    predicted = class_names[np.argmax(probs)]
    match = "✓" if predicted == expected else "✗"
    print(f"{match} Expected: {expected:8s} Got: {predicted:8s} ({probs.max()*100:.1f}%)")

# find good STRESSED test values from actual training data
import pandas as pd

df = pd.read_csv(SAVE_PATH + 'df_balanced.csv')
stressed = df[df['label'] == 2]

print("STRESSED feature ranges from real training data:")
print(stressed[['bpm_mean','hrv_rmssd','hrv_sdnn','spo2','motion_mean','motion_std']].describe().round(2))

print("\nTesting with real STRESSED samples:")
# test 5 actual stressed samples
for _, row in stressed.sample(5, random_state=42).iterrows():
    features = [row['bpm_mean'], row['hrv_rmssd'], row['hrv_sdnn'],
                row['spo2'], row['motion_mean'], row['motion_std']]
    probs = run_model_python(features)
    predicted = class_names[np.argmax(probs)]
    match = "✓" if predicted == "STRESSED" else "✗"
    print(f"{match} BPM:{features[0]:.1f} RMSSD:{features[1]:.1f} → {predicted} ({probs.max()*100:.1f}%)")