/*
 * biosense-rp2040 — wearable_biosense.ino
 *
 * Hardware:
 *   XIAO RP2040 + AD8232 ECG + MPU6050 (I2C) + SSD1306 OLED (I2C)
 *   MAX30102 SpO2 (future — synthetic placeholder until wired)
 *
 * Depends on:  model_weights.h   (generated by your Colab notebook)
 *              Adafruit SSD1306 + GFX libraries
 */

#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include "model_weights.h"          // your auto-generated weights + run_model()

// ── OLED ──────────────────────────────────────────────────────
#define OLED_W     128
#define OLED_H      64
Adafruit_SSD1306 oled(OLED_W, OLED_H, &Wire, -1);

// ── AD8232 ECG ────────────────────────────────────────────────
#define ECG_PIN    A0
#define LO_PLUS    D3
#define LO_MINUS   D4

// ── MPU6050 ───────────────────────────────────────────────────
#define MPU_ADDR   0x68

// ── Timing ────────────────────────────────────────────────────
#define WINDOW_MS  8000UL       // 8-second feature window
#define ECG_HZ     200          // sampling rate (matches your nsrdb pipeline)
#define ACCEL_HZ    50

// ── Buffers (sized for 8-second window) ───────────────────────
#define MAX_RR     80
#define MAX_ACCEL  400

float    rr_buf[MAX_RR];
uint8_t  rr_count = 0;
float    accel_buf[MAX_ACCEL];
uint16_t accel_count = 0;

// ECG peak detector state
uint32_t last_peak_ms = 0;
int      prev_ecg     = 512;
bool     in_peak      = false;
const int PEAK_THRESH = 580;    // tune to your electrode + skin contact

const char* CLASS_NAMES[4] = { "NORMAL", "ACTIVE", "STRESSED", "ALERT" };

// ─────────────────────────────────────────────────────────────
// MPU6050
// ─────────────────────────────────────────────────────────────
void mpu_init() {
    Wire.beginTransmission(MPU_ADDR);
    Wire.write(0x6B); Wire.write(0x00);   // wake
    Wire.endTransmission();
    Wire.beginTransmission(MPU_ADDR);
    Wire.write(0x1C); Wire.write(0x00);   // ±2g range
    Wire.endTransmission();
}

float read_accel_mag() {
    Wire.beginTransmission(MPU_ADDR);
    Wire.write(0x3B);
    Wire.endTransmission(false);
    Wire.requestFrom(MPU_ADDR, 6, true);
    int16_t ax = (Wire.read() << 8) | Wire.read();
    int16_t ay = (Wire.read() << 8) | Wire.read();
    int16_t az = (Wire.read() << 8) | Wire.read();
    float gx = ax / 16384.0f, gy = ay / 16384.0f, gz = az / 16384.0f;
    return sqrtf(gx*gx + gy*gy + gz*gz);
}

// ─────────────────────────────────────────────────────────────
// HRV features  (match your Python: rmssd in ms, sdnn in ms)
// ─────────────────────────────────────────────────────────────
float hrv_rmssd(float* rr, uint8_t n) {
    if (n < 2) return 0;
    float s = 0;
    for (uint8_t i = 1; i < n; i++) { float d = rr[i]-rr[i-1]; s += d*d; }
    return sqrtf(s / (n-1)) * 1000.0f;   // convert s->ms to match training
}

float hrv_sdnn(float* rr, uint8_t n) {
    if (n < 2) return 0;
    float mean = 0;
    for (uint8_t i = 0; i < n; i++) mean += rr[i];
    mean /= n;
    float v = 0;
    for (uint8_t i = 0; i < n; i++) { float d = rr[i]-mean; v += d*d; }
    return sqrtf(v / n) * 1000.0f;       // convert s->ms to match training
}

float arr_mean(float* a, uint16_t n) {
    float s = 0; for (uint16_t i = 0; i < n; i++) s += a[i]; return s / n;
}

float arr_std(float* a, uint16_t n, float mean) {
    float v = 0;
    for (uint16_t i = 0; i < n; i++) { float d = a[i]-mean; v += d*d; }
    return sqrtf(v / n);
}

// ─────────────────────────────────────────────────────────────
// SpO2  — synthetic until MAX30102 is wired
// Replace this function body with your MAX30102 driver read
// ─────────────────────────────────────────────────────────────
float get_spo2() {
    float v = 97.0f + (random(-30, 30) * 0.05f);
    return constrain(v, 90.0f, 100.0f);
}

// ─────────────────────────────────────────────────────────────
// ECG R-peak detector
// RR stored in seconds (your Python pipeline divides by sample rate)
// ─────────────────────────────────────────────────────────────
void process_ecg(int raw, uint32_t now_ms) {
    if (!in_peak && raw > PEAK_THRESH && raw > prev_ecg) {
        in_peak = true;
        if (last_peak_ms > 0) {
            float rr_s = (now_ms - last_peak_ms) / 1000.0f;
            if (rr_s > 0.25f && rr_s < 2.5f && rr_count < MAX_RR) {
                rr_buf[rr_count++] = rr_s;
            }
        }
        last_peak_ms = now_ms;
    }
    if (raw < PEAK_THRESH - 60) in_peak = false;
    prev_ecg = raw;
}

// ─────────────────────────────────────────────────────────────
// OLED display — one layout per class
// ─────────────────────────────────────────────────────────────
void show_state(uint8_t cls, float bpm, float spo2) {
    oled.clearDisplay();
    oled.setTextSize(1);
    oled.setTextColor(SSD1306_WHITE);

    switch (cls) {
        case 0:
            oled.setCursor(0, 0);  oled.println("Status: NORMAL");
            oled.setCursor(0,16);  oled.print("HR:   "); oled.print((int)bpm); oled.println(" bpm");
            oled.setCursor(0,28);  oled.print("SpO2: "); oled.print((int)spo2); oled.println("%");
            oled.setCursor(0,44);  oled.println("All clear");
            break;
        case 1:
            oled.setCursor(0, 0);  oled.println("Status: ACTIVE");
            oled.setCursor(0,16);  oled.print("HR:   "); oled.print((int)bpm); oled.println(" bpm");
            oled.setCursor(0,28);  oled.print("SpO2: "); oled.print((int)spo2); oled.println("%");
            oled.setCursor(0,44);  oled.println("Activity: Exercise");
            break;
        case 2:
            oled.setCursor(0, 0);  oled.println("Status: STRESSED");
            oled.setCursor(0,16);  oled.print("HR:   "); oled.print((int)bpm); oled.println(" bpm");
            oled.setCursor(0,28);  oled.print("SpO2: "); oled.print((int)spo2); oled.println("%");
            oled.setCursor(0,44);  oled.println("Rest / breathe");
            break;
        case 3:
            oled.setCursor(0, 0);  oled.println("!! ALERT !!");
            oled.setCursor(0,14);  oled.print("HR:   "); oled.print((int)bpm); oled.println(" bpm");
            oled.setCursor(0,26);  oled.print("SpO2: "); oled.print((int)spo2); oled.println("%");
            oled.setCursor(0,40);  oled.println("Check sensors");
            oled.setCursor(0,52);  oled.println("Possible abnormal");
            break;
    }
    oled.display();
}

// ─────────────────────────────────────────────────────────────
// setup / loop
// ─────────────────────────────────────────────────────────────
void setup() {
    Serial.begin(115200);
    pinMode(LO_PLUS,  INPUT);
    pinMode(LO_MINUS, INPUT);

    Wire.begin();
    mpu_init();

    if (!oled.begin(SSD1306_SWITCHCAPVCC, 0x3C)) {
        Serial.println("OLED failed"); while (1);
    }
    oled.clearDisplay();
    oled.setTextSize(1); oled.setTextColor(SSD1306_WHITE);
    oled.setCursor(20,20); oled.println("BioSense RP2040");
    oled.setCursor(28,36); oled.println("Starting...");
    oled.display();
    delay(1500);
    Serial.println("=== BioSense RP2040 ready ===");
}

void loop() {
    rr_count = 0; accel_count = 0;

    uint32_t t0 = millis(), t_ecg = 0, t_acc = 0;
    uint32_t ecg_iv  = 1000UL / ECG_HZ;    // 5 ms
    uint32_t acc_iv  = 1000UL / ACCEL_HZ;  // 20 ms

    // ── Collect 8-second window ──────────────────────────
    while (millis() - t0 < WINDOW_MS) {
        uint32_t now = millis();
        if (now - t_ecg >= ecg_iv) {
            t_ecg = now;
            if (!digitalRead(LO_PLUS) && !digitalRead(LO_MINUS))
                process_ecg(analogRead(ECG_PIN), now);
        }
        if (now - t_acc >= acc_iv && accel_count < MAX_ACCEL) {
            t_acc = now;
            accel_buf[accel_count++] = read_accel_mag();
        }
    }

    // ── Compute features ─────────────────────────────────
    float bpm_mean, rmssd_val, sdnn_val;
    if (rr_count >= 2) {
        float rr_mean = arr_mean(rr_buf, rr_count);
        bpm_mean  = 60.0f / rr_mean;
        rmssd_val = hrv_rmssd(rr_buf, rr_count);
        sdnn_val  = hrv_sdnn(rr_buf, rr_count);
    } else {
        bpm_mean = 72.0f; rmssd_val = 40.0f; sdnn_val = 40.0f;
    }

    float spo2_val  = get_spo2();
    float m_mean    = arr_mean(accel_buf, accel_count);
    float m_std     = arr_std(accel_buf, accel_count, m_mean);

    // ── Inference via model_weights.h ────────────────────
    // run_model() applies the scaler internally then does 6->32->16->4
    float raw[6]   = { bpm_mean, rmssd_val, sdnn_val, spo2_val, m_mean, m_std };
    float probs[4] = { 0, 0, 0, 0 };
    run_model(raw, probs);

    uint8_t cls = 0;
    for (uint8_t i = 1; i < 4; i++)
        if (probs[i] > probs[cls]) cls = i;

    // ── Output ───────────────────────────────────────────
    show_state(cls, bpm_mean, spo2_val);

    Serial.printf("[%s] bpm=%.1f rmssd=%.1f sdnn=%.1f spo2=%.1f "
                  "m_mean=%.3f m_std=%.3f conf=%.0f%% (rr_n=%d)\n",
        CLASS_NAMES[cls], bpm_mean, rmssd_val, sdnn_val,
        spo2_val, m_mean, m_std, probs[cls]*100, rr_count);
}
